In [1]:
import numpy as np

In [ ]:
# np.random.rand(shape) takes shape as argument
np.random.rand(2,3) # generates an ndArray with specified shape with random numbers between 0 and 1

array([[0.77231532, 0.51594721, 0.49393587],
       [0.15081   , 0.73556721, 0.2500869 ]])

In [15]:
# randInt
print(np.random.randint(0, 10)) 
# generates a random integer between a specified range

print(np.random.randint(0, 10, 5)) 
# print(type(np.random.randint(0, 10, 5))) 
# generates an ndarray of 5 random integers between the specified range

print(np.random.randint(0, 10, (2, 3)))
# generates an ndarray of specified shape and fill it with random integers between the specified range

4
[1 6 9 9 5]
[[4 4 0]
 [1 1 8]]


In [ ]:
# randn(shape) --> generates an ndarray of normal distribution for the given shape

# np.random.randn(3)
np.random.randn(2,3)

array([[-0.76551329,  0.69703302, -0.56521346],
       [-0.2203663 ,  1.31302879, -0.78140761]])

In [ ]:
# choice(options, size)

np.random.choice([10, 20, 30]) # choses one among the list of options
# np.random.choice([1,2,3,4], size=2) choses the specified number of options and returns an ndarray of chosen options

numpy.int64

In [ ]:
print(np.random.seed(42))
